# Generated by Django 5.1.2 on 2024-11-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_remove_pumpstatushistory_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pumpStatus', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PumpStatusHistory',
        ),
        migrations.AlterField(
            model_name='soilmoisturedata',
            name='moisture_level',
            field=models.FloatField(),
        ),
    ]
