# Generated by Django 5.1.1 on 2024-11-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_pumpdata_delete_pumpstatushistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpdata',
            name='pumpStatus',
            field=models.CharField(max_length=10),
        ),
    ]
