# Generated by Django 5.1.1 on 2024-12-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_pumpdata_pumpstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='camera_images/')),
            ],
        ),
    ]
