# Generated by Django 5.1.2 on 2024-12-16 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_cameraimagedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CameraImageData',
        ),
    ]
